{{/*
SOURCE: operators/cinder/config/rbac/role.yaml (ClusterRole cinder-webhook)
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/cinder that carry roleName=cinder-webhook; do not edit.
No leases rule: a standalone webhook elects no leader.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "cinder-operator.webhookRbacRules" -}}
- apiGroups:
  - cinder.openstack.c5c3.io
  resources:
  - cinderbackupbackends
  verbs:
  - list
- apiGroups:
  - cinder.openstack.c5c3.io
  resources:
  - cinders
  verbs:
  - get
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
{{- end }}
