{{/*
SOURCE: operators/glance/config/rbac/role.yaml
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/glance; do not edit. The leases rule is appended for leader election.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "glance-operator.rbacRules" -}}
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - clustersecretstores
  - externalsecrets
  - secretstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  verbs:
  - get
- apiGroups:
  - glance.openstack.c5c3.io
  resources:
  - glancebackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - glance.openstack.c5c3.io
  resources:
  - glancebackends/status
  - glances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - glance.openstack.c5c3.io
  resources:
  - glances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - glance.openstack.c5c3.io
  resources:
  - glances/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.mariadb.com
  resources:
  - databases
  - grants
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.mariadb.com
  resources:
  - mariadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }}
