{{/*
SOURCE: operators/glance/config/rbac/role.yaml (ClusterRole glance-webhook)
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/glance that carry roleName=glance-webhook; do not edit.
No leases rule: a standalone webhook elects no leader.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "glance-operator.webhookRbacRules" -}}
- apiGroups:
  - glance.openstack.c5c3.io
  resources:
  - glancebackends
  verbs:
  - list
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
{{- end }}
