{{/*
SOURCE: operators/barbican/config/rbac/role.yaml (ClusterRole barbican-webhook)
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/barbican that carry roleName=barbican-webhook; do not edit.
No leases rule: a standalone webhook elects no leader.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "barbican-operator.webhookRbacRules" -}}
- apiGroups:
  - barbican.openstack.c5c3.io
  resources:
  - barbicansecretstores
  verbs:
  - list
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
{{- end }}
