//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/c5c3/cobaltcore/internal/common/types"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNBackupS3Spec) DeepCopyInto(out *OVNBackupS3Spec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNBackupS3Spec.
func (in *OVNBackupS3Spec) DeepCopy() *OVNBackupS3Spec {
	if in == nil {
		return nil
	}
	out := new(OVNBackupS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNBackupSpec) DeepCopyInto(out *OVNBackupSpec) {
	*out = *in
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(OVNBackupS3Spec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNBackupSpec.
func (in *OVNBackupSpec) DeepCopy() *OVNBackupSpec {
	if in == nil {
		return nil
	}
	out := new(OVNBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNBridgeMapping) DeepCopyInto(out *OVNBridgeMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNBridgeMapping.
func (in *OVNBridgeMapping) DeepCopy() *OVNBridgeMapping {
	if in == nil {
		return nil
	}
	out := new(OVNBridgeMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNCentral) DeepCopyInto(out *OVNCentral) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNCentral.
func (in *OVNCentral) DeepCopy() *OVNCentral {
	if in == nil {
		return nil
	}
	out := new(OVNCentral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNCentral) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNCentralList) DeepCopyInto(out *OVNCentralList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVNCentral, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNCentralList.
func (in *OVNCentralList) DeepCopy() *OVNCentralList {
	if in == nil {
		return nil
	}
	out := new(OVNCentralList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNCentralList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNCentralRef) DeepCopyInto(out *OVNCentralRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNCentralRef.
func (in *OVNCentralRef) DeepCopy() *OVNCentralRef {
	if in == nil {
		return nil
	}
	out := new(OVNCentralRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNCentralSpec) DeepCopyInto(out *OVNCentralSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	in.Northbound.DeepCopyInto(&out.Northbound)
	in.Southbound.DeepCopyInto(&out.Southbound)
	in.Northd.DeepCopyInto(&out.Northd)
	if in.Relay != nil {
		in, out := &in.Relay, &out.Relay
		*out = new(OVNRelaySpec)
		(*in).DeepCopyInto(*out)
	}
	out.TLS = in.TLS
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(OVNBackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNCentralSpec.
func (in *OVNCentralSpec) DeepCopy() *OVNCentralSpec {
	if in == nil {
		return nil
	}
	out := new(OVNCentralSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNCentralStatus) DeepCopyInto(out *OVNCentralStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Northbound = in.Northbound
	out.Southbound = in.Southbound
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNCentralStatus.
func (in *OVNCentralStatus) DeepCopy() *OVNCentralStatus {
	if in == nil {
		return nil
	}
	out := new(OVNCentralStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNChassis) DeepCopyInto(out *OVNChassis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNChassis.
func (in *OVNChassis) DeepCopy() *OVNChassis {
	if in == nil {
		return nil
	}
	out := new(OVNChassis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNChassis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNChassisContainerSpec) DeepCopyInto(out *OVNChassisContainerSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNChassisContainerSpec.
func (in *OVNChassisContainerSpec) DeepCopy() *OVNChassisContainerSpec {
	if in == nil {
		return nil
	}
	out := new(OVNChassisContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNChassisList) DeepCopyInto(out *OVNChassisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVNChassis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNChassisList.
func (in *OVNChassisList) DeepCopy() *OVNChassisList {
	if in == nil {
		return nil
	}
	out := new(OVNChassisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNChassisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNChassisNodeStatus) DeepCopyInto(out *OVNChassisNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNChassisNodeStatus.
func (in *OVNChassisNodeStatus) DeepCopy() *OVNChassisNodeStatus {
	if in == nil {
		return nil
	}
	out := new(OVNChassisNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNChassisSpec) DeepCopyInto(out *OVNChassisSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(types.ImageSpec)
		**out = **in
	}
	out.CentralRef = in.CentralRef
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(OVNGatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BridgeMappings != nil {
		in, out := &in.BridgeMappings, &out.BridgeMappings
		*out = make([]OVNBridgeMapping, len(*in))
		copy(*out, *in)
	}
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
	if in.OVS != nil {
		in, out := &in.OVS, &out.OVS
		*out = new(OVNChassisContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(OVNChassisContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNChassisSpec.
func (in *OVNChassisSpec) DeepCopy() *OVNChassisSpec {
	if in == nil {
		return nil
	}
	out := new(OVNChassisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNChassisStatus) DeepCopyInto(out *OVNChassisStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]OVNChassisNodeStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNChassisStatus.
func (in *OVNChassisStatus) DeepCopy() *OVNChassisStatus {
	if in == nil {
		return nil
	}
	out := new(OVNChassisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNChassisUpdateStrategy) DeepCopyInto(out *OVNChassisUpdateStrategy) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNChassisUpdateStrategy.
func (in *OVNChassisUpdateStrategy) DeepCopy() *OVNChassisUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(OVNChassisUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDatabaseSpec) DeepCopyInto(out *OVNDatabaseSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.NodePortBase != nil {
		in, out := &in.NodePortBase, &out.NodePortBase
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDatabaseSpec.
func (in *OVNDatabaseSpec) DeepCopy() *OVNDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(OVNDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDatabaseStatus) DeepCopyInto(out *OVNDatabaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDatabaseStatus.
func (in *OVNDatabaseStatus) DeepCopy() *OVNDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(OVNDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNGatewaySpec) DeepCopyInto(out *OVNGatewaySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNGatewaySpec.
func (in *OVNGatewaySpec) DeepCopy() *OVNGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(OVNGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNIssuerRef) DeepCopyInto(out *OVNIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNIssuerRef.
func (in *OVNIssuerRef) DeepCopy() *OVNIssuerRef {
	if in == nil {
		return nil
	}
	out := new(OVNIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNNorthdSpec) DeepCopyInto(out *OVNNorthdSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNNorthdSpec.
func (in *OVNNorthdSpec) DeepCopy() *OVNNorthdSpec {
	if in == nil {
		return nil
	}
	out := new(OVNNorthdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNRelaySpec) DeepCopyInto(out *OVNRelaySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNRelaySpec.
func (in *OVNRelaySpec) DeepCopy() *OVNRelaySpec {
	if in == nil {
		return nil
	}
	out := new(OVNRelaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNStorageSpec) DeepCopyInto(out *OVNStorageSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNStorageSpec.
func (in *OVNStorageSpec) DeepCopy() *OVNStorageSpec {
	if in == nil {
		return nil
	}
	out := new(OVNStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNTLSSpec) DeepCopyInto(out *OVNTLSSpec) {
	*out = *in
	out.IssuerRef = in.IssuerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNTLSSpec.
func (in *OVNTLSSpec) DeepCopy() *OVNTLSSpec {
	if in == nil {
		return nil
	}
	out := new(OVNTLSSpec)
	in.DeepCopyInto(out)
	return out
}
