//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/c5c3/cobaltcore/internal/common/types"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanKeyManagerSpec) DeepCopyInto(out *BarbicanKeyManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanKeyManagerSpec.
func (in *BarbicanKeyManagerSpec) DeepCopy() *BarbicanKeyManagerSpec {
	if in == nil {
		return nil
	}
	out := new(BarbicanKeyManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cinder) DeepCopyInto(out *Cinder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cinder.
func (in *Cinder) DeepCopy() *Cinder {
	if in == nil {
		return nil
	}
	out := new(Cinder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cinder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderAPISpec) DeepCopyInto(out *CinderAPISpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	if in.UWSGI != nil {
		in, out := &in.UWSGI, &out.UWSGI
		*out = new(UWSGISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderAPISpec.
func (in *CinderAPISpec) DeepCopy() *CinderAPISpec {
	if in == nil {
		return nil
	}
	out := new(CinderAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackend) DeepCopyInto(out *CinderBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackend.
func (in *CinderBackend) DeepCopy() *CinderBackend {
	if in == nil {
		return nil
	}
	out := new(CinderBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CinderBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackendList) DeepCopyInto(out *CinderBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CinderBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackendList.
func (in *CinderBackendList) DeepCopy() *CinderBackendList {
	if in == nil {
		return nil
	}
	out := new(CinderBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CinderBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackendSpec) DeepCopyInto(out *CinderBackendSpec) {
	*out = *in
	out.CinderRef = in.CinderRef
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSBackendSpec)
		**out = **in
	}
	if in.ImageVolumeCache != nil {
		in, out := &in.ImageVolumeCache, &out.ImageVolumeCache
		*out = new(ImageVolumeCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraOptions != nil {
		in, out := &in.ExtraOptions, &out.ExtraOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackendSpec.
func (in *CinderBackendSpec) DeepCopy() *CinderBackendSpec {
	if in == nil {
		return nil
	}
	out := new(CinderBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackendStatus) DeepCopyInto(out *CinderBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackendStatus.
func (in *CinderBackendStatus) DeepCopy() *CinderBackendStatus {
	if in == nil {
		return nil
	}
	out := new(CinderBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackupBackend) DeepCopyInto(out *CinderBackupBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackupBackend.
func (in *CinderBackupBackend) DeepCopy() *CinderBackupBackend {
	if in == nil {
		return nil
	}
	out := new(CinderBackupBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CinderBackupBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackupBackendList) DeepCopyInto(out *CinderBackupBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CinderBackupBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackupBackendList.
func (in *CinderBackupBackendList) DeepCopy() *CinderBackupBackendList {
	if in == nil {
		return nil
	}
	out := new(CinderBackupBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CinderBackupBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackupBackendSpec) DeepCopyInto(out *CinderBackupBackendSpec) {
	*out = *in
	out.CinderRef = in.CinderRef
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSBackupBackendSpec)
		**out = **in
	}
	if in.FileSize != nil {
		in, out := &in.FileSize, &out.FileSize
		*out = new(int64)
		**out = **in
	}
	if in.ExtraOptions != nil {
		in, out := &in.ExtraOptions, &out.ExtraOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackupBackendSpec.
func (in *CinderBackupBackendSpec) DeepCopy() *CinderBackupBackendSpec {
	if in == nil {
		return nil
	}
	out := new(CinderBackupBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackupBackendStatus) DeepCopyInto(out *CinderBackupBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackupBackendStatus.
func (in *CinderBackupBackendStatus) DeepCopy() *CinderBackupBackendStatus {
	if in == nil {
		return nil
	}
	out := new(CinderBackupBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderBackupSpec) DeepCopyInto(out *CinderBackupSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderBackupSpec.
func (in *CinderBackupSpec) DeepCopy() *CinderBackupSpec {
	if in == nil {
		return nil
	}
	out := new(CinderBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderList) DeepCopyInto(out *CinderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cinder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderList.
func (in *CinderList) DeepCopy() *CinderList {
	if in == nil {
		return nil
	}
	out := new(CinderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CinderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderRefSpec) DeepCopyInto(out *CinderRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderRefSpec.
func (in *CinderRefSpec) DeepCopy() *CinderRefSpec {
	if in == nil {
		return nil
	}
	out := new(CinderRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderSchedulerSpec) DeepCopyInto(out *CinderSchedulerSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderSchedulerSpec.
func (in *CinderSchedulerSpec) DeepCopy() *CinderSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(CinderSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderSpec) DeepCopyInto(out *CinderSpec) {
	*out = *in
	out.Image = in.Image
	in.Database.DeepCopyInto(&out.Database)
	in.Cache.DeepCopyInto(&out.Cache)
	in.Messaging.DeepCopyInto(&out.Messaging)
	in.API.DeepCopyInto(&out.API)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
	in.Volume.DeepCopyInto(&out.Volume)
	in.Backup.DeepCopyInto(&out.Backup)
	if in.ServiceUser != nil {
		in, out := &in.ServiceUser, &out.ServiceUser
		*out = new(ServiceUserSpec)
		**out = **in
	}
	if in.KeyManager != nil {
		in, out := &in.KeyManager, &out.KeyManager
		*out = new(KeyManagerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalTenant != nil {
		in, out := &in.InternalTenant, &out.InternalTenant
		*out = new(InternalTenantSpec)
		**out = **in
	}
	if in.DBPurge != nil {
		in, out := &in.DBPurge, &out.DBPurge
		*out = new(DBPurgeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SecretStoreRef != nil {
		in, out := &in.SecretStoreRef, &out.SecretStoreRef
		*out = new(types.SecretStoreRefSpec)
		**out = **in
	}
	if in.PolicyOverrides != nil {
		in, out := &in.PolicyOverrides, &out.PolicyOverrides
		*out = new(types.PolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderSpec.
func (in *CinderSpec) DeepCopy() *CinderSpec {
	if in == nil {
		return nil
	}
	out := new(CinderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderStatus) DeepCopyInto(out *CinderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeServices != nil {
		in, out := &in.VolumeServices, &out.VolumeServices
		*out = make([]VolumeServiceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderStatus.
func (in *CinderStatus) DeepCopy() *CinderStatus {
	if in == nil {
		return nil
	}
	out := new(CinderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CinderVolumeSpec) DeepCopyInto(out *CinderVolumeSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CinderVolumeSpec.
func (in *CinderVolumeSpec) DeepCopy() *CinderVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(CinderVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBPurgeSpec) DeepCopyInto(out *DBPurgeSpec) {
	*out = *in
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBPurgeSpec.
func (in *DBPurgeSpec) DeepCopy() *DBPurgeSpec {
	if in == nil {
		return nil
	}
	out := new(DBPurgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageVolumeCacheSpec) DeepCopyInto(out *ImageVolumeCacheSpec) {
	*out = *in
	if in.MaxSizeGB != nil {
		in, out := &in.MaxSizeGB, &out.MaxSizeGB
		*out = new(int32)
		**out = **in
	}
	if in.MaxCount != nil {
		in, out := &in.MaxCount, &out.MaxCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageVolumeCacheSpec.
func (in *ImageVolumeCacheSpec) DeepCopy() *ImageVolumeCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ImageVolumeCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalTenantSpec) DeepCopyInto(out *InternalTenantSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalTenantSpec.
func (in *InternalTenantSpec) DeepCopy() *InternalTenantSpec {
	if in == nil {
		return nil
	}
	out := new(InternalTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManagerSpec) DeepCopyInto(out *KeyManagerSpec) {
	*out = *in
	if in.Barbican != nil {
		in, out := &in.Barbican, &out.Barbican
		*out = new(BarbicanKeyManagerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManagerSpec.
func (in *KeyManagerSpec) DeepCopy() *KeyManagerSpec {
	if in == nil {
		return nil
	}
	out := new(KeyManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSBackendSpec) DeepCopyInto(out *NFSBackendSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSBackendSpec.
func (in *NFSBackendSpec) DeepCopy() *NFSBackendSpec {
	if in == nil {
		return nil
	}
	out := new(NFSBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSBackupBackendSpec) DeepCopyInto(out *NFSBackupBackendSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSBackupBackendSpec.
func (in *NFSBackupBackendSpec) DeepCopy() *NFSBackupBackendSpec {
	if in == nil {
		return nil
	}
	out := new(NFSBackupBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceUserSpec) DeepCopyInto(out *ServiceUserSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceUserSpec.
func (in *ServiceUserSpec) DeepCopy() *ServiceUserSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeServiceStatus) DeepCopyInto(out *VolumeServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeServiceStatus.
func (in *VolumeServiceStatus) DeepCopy() *VolumeServiceStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeServiceStatus)
	in.DeepCopyInto(out)
	return out
}
