---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-neutron-openstack-c5c3-io-v1alpha1-neutron
  failurePolicy: Fail
  name: mneutron.kb.io
  rules:
  - apiGroups:
    - neutron.openstack.c5c3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - neutrons
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-neutron-openstack-c5c3-io-v1alpha1-neutronmetadataagent
  failurePolicy: Fail
  name: mneutronmetadataagent.kb.io
  rules:
  - apiGroups:
    - neutron.openstack.c5c3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - neutronmetadataagents
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-neutron-openstack-c5c3-io-v1alpha1-neutron
  failurePolicy: Fail
  name: vneutron.kb.io
  rules:
  - apiGroups:
    - neutron.openstack.c5c3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - neutrons
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-neutron-openstack-c5c3-io-v1alpha1-neutronmetadataagent
  failurePolicy: Fail
  name: vneutronmetadataagent.kb.io
  rules:
  - apiGroups:
    - neutron.openstack.c5c3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - neutronmetadataagents
  sideEffects: None
