#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

"""Generate each operator chart's RBAC rules template from controller-gen output.

The kubebuilder RBAC markers in an operator's Go sources are the single source
of truth for what its ServiceAccount may do. `make manifests` has controller-gen
render them to operators/<op>/config/rbac/role.yaml; this script copies the
rules of that ClusterRole into the chart as the "<op>-operator.rbacRules" named
template (templates/_rbac-rules.tpl), which the operator-library ClusterRole and
Role templates include. One rule is appended that no marker carries: leases in
coordination.k8s.io, which the manager's leader election needs.

The rationale for individual grants lives as comments next to the markers; the
generated template carries none, so edit the markers, not this output.

Charts are discovered from the repository layout (operators/<op>/helm/<op>-operator).
Run via the Makefile:

  make sync-helm-rbac    # regenerate every chart's templates/_rbac-rules.tpl
  make verify-helm-rbac  # exit non-zero if any committed file is stale
"""

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

LEADER_ELECTION_RULE = {
    "apiGroups": ["coordination.k8s.io"],
    "resources": ["leases"],
    "verbs": ["get", "list", "watch", "create", "update", "patch", "delete"],
}


def discover_charts():
    """Return (operator, chart directory) pairs for every operator chart."""
    charts = []
    for chart_dir in sorted(REPO_ROOT.glob("operators/*/helm/*-operator")):
        op = chart_dir.parent.parent.name
        if chart_dir.name != f"{op}-operator":
            sys.exit(f"error: {chart_dir} does not follow the operators/<op>/helm/<op>-operator layout")
        charts.append((op, chart_dir))
    return charts


def render(op):
    """Return the exact text of the chart's templates/_rbac-rules.tpl."""
    source = Path("operators") / op / "config" / "rbac" / "role.yaml"
    path = REPO_ROOT / source
    if not path.exists():
        sys.exit(f"error: {source} missing; run 'make manifests' first")
    role = yaml.safe_load(path.read_text(encoding="utf-8"))
    rules = list(role.get("rules") or []) + [LEADER_ELECTION_RULE]
    body = yaml.safe_dump(rules, sort_keys=False, default_flow_style=False, width=1000)
    return (
        "{{/*\n"
        f"SOURCE: {source}\n"
        "GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in\n"
        f"operators/{op}; do not edit. The leases rule is appended for leader election.\n"
        "Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.\n"
        "*/}}\n"
        f'{{{{- define "{op}-operator.rbacRules" -}}}}\n'
        f"{body}"
        "{{- end }}\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero (without writing) if any committed file is stale",
    )
    args = parser.parse_args()

    drift = False
    for op, chart_dir in discover_charts():
        path = chart_dir / "templates" / "_rbac-rules.tpl"
        rel = path.relative_to(REPO_ROOT)
        want = render(op)
        if args.check:
            have = path.read_text(encoding="utf-8") if path.exists() else ""
            if have != want:
                drift = True
                print(f"DRIFT: {rel} is out of sync with operators/{op}/config/rbac/role.yaml")
        else:
            path.write_text(want, encoding="utf-8")
            print(f"wrote {rel}")

    if args.check and drift:
        print("Helm RBAC rules drift detected. Run 'make sync-helm-rbac'.")
        return 1
    if args.check:
        print("Helm RBAC rules check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
