//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/c5c3/forge/internal/common/types"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerSpec) DeepCopyInto(out *APIServerSpec) {
	*out = *in
	if in.UWSGI != nil {
		in, out := &in.UWSGI, &out.UWSGI
		*out = new(UWSGISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerSpec.
func (in *APIServerSpec) DeepCopy() *APIServerSpec {
	if in == nil {
		return nil
	}
	out := new(APIServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Barbican) DeepCopyInto(out *Barbican) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Barbican.
func (in *Barbican) DeepCopy() *Barbican {
	if in == nil {
		return nil
	}
	out := new(Barbican)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Barbican) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanList) DeepCopyInto(out *BarbicanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Barbican, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanList.
func (in *BarbicanList) DeepCopy() *BarbicanList {
	if in == nil {
		return nil
	}
	out := new(BarbicanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BarbicanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanRefSpec) DeepCopyInto(out *BarbicanRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanRefSpec.
func (in *BarbicanRefSpec) DeepCopy() *BarbicanRefSpec {
	if in == nil {
		return nil
	}
	out := new(BarbicanRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanSecretStore) DeepCopyInto(out *BarbicanSecretStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanSecretStore.
func (in *BarbicanSecretStore) DeepCopy() *BarbicanSecretStore {
	if in == nil {
		return nil
	}
	out := new(BarbicanSecretStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BarbicanSecretStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanSecretStoreList) DeepCopyInto(out *BarbicanSecretStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BarbicanSecretStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanSecretStoreList.
func (in *BarbicanSecretStoreList) DeepCopy() *BarbicanSecretStoreList {
	if in == nil {
		return nil
	}
	out := new(BarbicanSecretStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BarbicanSecretStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanSecretStoreSpec) DeepCopyInto(out *BarbicanSecretStoreSpec) {
	*out = *in
	out.BarbicanRef = in.BarbicanRef
	if in.OpenBao != nil {
		in, out := &in.OpenBao, &out.OpenBao
		*out = new(OpenBaoStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraOptions != nil {
		in, out := &in.ExtraOptions, &out.ExtraOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanSecretStoreSpec.
func (in *BarbicanSecretStoreSpec) DeepCopy() *BarbicanSecretStoreSpec {
	if in == nil {
		return nil
	}
	out := new(BarbicanSecretStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanSecretStoreStatus) DeepCopyInto(out *BarbicanSecretStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanSecretStoreStatus.
func (in *BarbicanSecretStoreStatus) DeepCopy() *BarbicanSecretStoreStatus {
	if in == nil {
		return nil
	}
	out := new(BarbicanSecretStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanSpec) DeepCopyInto(out *BarbicanSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	out.Image = in.Image
	in.Database.DeepCopyInto(&out.Database)
	in.Cache.DeepCopyInto(&out.Cache)
	out.ServiceUser = in.ServiceUser
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(APIServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DBClean != nil {
		in, out := &in.DBClean, &out.DBClean
		*out = new(DBCleanSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretStoreRef != nil {
		in, out := &in.SecretStoreRef, &out.SecretStoreRef
		*out = new(types.SecretStoreRefSpec)
		**out = **in
	}
	if in.TargetClusterRef != nil {
		in, out := &in.TargetClusterRef, &out.TargetClusterRef
		*out = new(types.TargetClusterRefSpec)
		**out = **in
	}
	if in.PolicyOverrides != nil {
		in, out := &in.PolicyOverrides, &out.PolicyOverrides
		*out = new(types.PolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Middleware != nil {
		in, out := &in.Middleware, &out.Middleware
		*out = make([]types.MiddlewareSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]types.PluginSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanSpec.
func (in *BarbicanSpec) DeepCopy() *BarbicanSpec {
	if in == nil {
		return nil
	}
	out := new(BarbicanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarbicanStatus) DeepCopyInto(out *BarbicanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProjectedSecretStores != nil {
		in, out := &in.ProjectedSecretStores, &out.ProjectedSecretStores
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProjectedSecretStoreHosts != nil {
		in, out := &in.ProjectedSecretStoreHosts, &out.ProjectedSecretStoreHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarbicanStatus.
func (in *BarbicanStatus) DeepCopy() *BarbicanStatus {
	if in == nil {
		return nil
	}
	out := new(BarbicanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBCleanSpec) DeepCopyInto(out *DBCleanSpec) {
	*out = *in
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.SoftDeleteExpiredSecrets != nil {
		in, out := &in.SoftDeleteExpiredSecrets, &out.SoftDeleteExpiredSecrets
		*out = new(bool)
		**out = **in
	}
	if in.CleanUnassociatedProjects != nil {
		in, out := &in.CleanUnassociatedProjects, &out.CleanUnassociatedProjects
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBCleanSpec.
func (in *DBCleanSpec) DeepCopy() *DBCleanSpec {
	if in == nil {
		return nil
	}
	out := new(DBCleanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRefSpec) DeepCopyInto(out *InstanceRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRefSpec.
func (in *InstanceRefSpec) DeepCopy() *InstanceRefSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoServerSpec) DeepCopyInto(out *OpenBaoServerSpec) {
	*out = *in
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(SecretNameRefSpec)
		**out = **in
	}
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoServerSpec.
func (in *OpenBaoServerSpec) DeepCopy() *OpenBaoServerSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoStoreSpec) DeepCopyInto(out *OpenBaoStoreSpec) {
	*out = *in
	if in.InstanceRef != nil {
		in, out := &in.InstanceRef, &out.InstanceRef
		*out = new(InstanceRefSpec)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(OpenBaoServerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoStoreSpec.
func (in *OpenBaoStoreSpec) DeepCopy() *OpenBaoStoreSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretNameRefSpec) DeepCopyInto(out *SecretNameRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretNameRefSpec.
func (in *SecretNameRefSpec) DeepCopy() *SecretNameRefSpec {
	if in == nil {
		return nil
	}
	out := new(SecretNameRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceUserSpec) DeepCopyInto(out *ServiceUserSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceUserSpec.
func (in *ServiceUserSpec) DeepCopy() *ServiceUserSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceUserSpec)
	in.DeepCopyInto(out)
	return out
}
