{{/*
SOURCE: operators/placement/config/rbac/role.yaml (ClusterRole placement-webhook)
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/placement that carry roleName=placement-webhook; do not edit.
No leases rule: a standalone webhook elects no leader.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "placement-operator.webhookRbacRules" -}}
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
{{- end }}
