{{/*
SOURCE: operators/nova/config/rbac/role.yaml (ClusterRole nova-webhook)
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/nova that carry roleName=nova-webhook; do not edit.
No leases rule: a standalone webhook elects no leader.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "nova-operator.webhookRbacRules" -}}
- apiGroups:
  - nova.openstack.c5c3.io
  resources:
  - novas
  verbs:
  - get
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
{{- end }}
