{{/*
SOURCE: operators/c5c3/config/rbac/role.yaml (ClusterRole c5c3-webhook)
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/c5c3 that carry roleName=c5c3-webhook; do not edit.
No leases rule: a standalone webhook elects no leader.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "c5c3-operator.webhookRbacRules" -}}
- apiGroups:
  - c5c3.io
  resources:
  - controlplanes
  verbs:
  - list
- apiGroups:
  - c5c3.io
  resources:
  - sizingprofiles
  verbs:
  - get
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
{{- end }}
