{{/*
SOURCE: operators/ovn/config/rbac/role.yaml
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/ovn; do not edit. The leases rule is appended for leader election.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "ovn-operator.rbacRules" -}}
- apiGroups:
  - ''
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - nodes
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.c5c3.io
  resources:
  - ovncentrals
  - ovnchassis
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.c5c3.io
  resources:
  - ovncentrals/finalizers
  - ovnchassis/finalizers
  verbs:
  - update
- apiGroups:
  - ovn.openstack.c5c3.io
  resources:
  - ovncentrals/status
  - ovnchassis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }}
