{{/*
SOURCE: operators/keystone/config/rbac/role.yaml (ClusterRole keystone-webhook)
GENERATED by hack/gen-helm-rbac-rules.py from the kubebuilder RBAC markers in
operators/keystone that carry roleName=keystone-webhook; do not edit.
No leases rule: a standalone webhook elects no leader.
Run 'make verify-helm-rbac' to check for drift, or 'make sync-helm-rbac' to update.
*/}}
{{- define "keystone-operator.webhookRbacRules" -}}
- apiGroups:
  - keystone.openstack.c5c3.io
  resources:
  - keystoneidentitybackends
  verbs:
  - list
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
{{- end }}
